/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-01-25 06:31:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.vac;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vacApply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>휴가신청</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/vacApply.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t<span id=\"title\">휴가신청</span>\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id=\"emplInfo\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>사번</th>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.emplNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<th>사원명</th>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.emplNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<th>부서</th>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.dept.deptNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t<th>총 휴가일수</th>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.vacHistory.vcatnAmount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 일</td>\r\n");
      out.write("\t\t\t<th>잔여 휴가일수</th>\r\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.vacHistory.vcatnLeft }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 일</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"searchUI\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>휴가코드</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" class=\"code\" name=\"vcatnCode\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"small-search\" data-action=\"vcatnSearch\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"searchImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Search.png\">\r\n");
      out.write("\t\t\t\t\t\t</button><input type=\"text\" class=\"nm\" name=\"vcatnNm\" placeholder=\"휴가코드\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>작성일자</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"date\" name=\"vacstusStart\">\r\n");
      out.write("\t\t\t\t\t\t&ensp;~&ensp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"date\" name=\"vacstusEnd\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>휴가사유</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"vacstusSumry\" placeholder=\"적요\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class='btnArea'>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"searchBtn\" value=\"검색\"><input type=\"reset\" value=\"초기화\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id=\"list-table\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>휴가명</th>\r\n");
      out.write("\t\t\t\t<th>휴가기간</th>\r\n");
      out.write("\t\t\t\t<th id=\"resn\">휴가사유</th>\r\n");
      out.write("\t\t\t\t<th>반차여부</th>\r\n");
      out.write("\t\t\t\t<th>진행상태</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody></tbody>\r\n");
      out.write("\t\t<tfoot>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t<div id=\"pagingArea\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tfoot>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"bottom\">\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t\t<button type=\"button\" id=\"insert\">신청</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form class=\"draftInfo\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"draftTitle\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form id=\"searchForm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"page\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"vcatnCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.vcatnCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"vacstusStart\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.vacstusStart }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"vacstusEnd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.vacstusEnd }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"vacstusSumry\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.vacstusSumry }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<input type=\"hidden\" id=\"nm\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"code\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/paging.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//검색 버튼\r\n");
      out.write("\t\t$(\".small-search\").on(\"click\", function(){\r\n");
      out.write("\t\t\taction = $(this).data(\"action\");\r\n");
      out.write("\t\t\tcode = $(this).parents(\"td\").find(\".code\");\r\n");
      out.write("\t\t\tnm = $(this).parents(\"td\").find(\".nm\");\r\n");
      out.write("\t\t\tvar nWidth = 900;\r\n");
      out.write("\t\t\tvar nHeight = 950;\r\n");
      out.write("\t\t\tvar curX = window.screenLeft;\r\n");
      out.write("\t\t\tvar curY = window.screenTop;\r\n");
      out.write("\t\t\tvar curWidth = document.body.clientWidth;\r\n");
      out.write("\t\t\tvar curHeight = document.body.clientHeight;\r\n");
      out.write("\t\t\tvar nLeft = curX + (curWidth / 2) - (nWidth / 2);\r\n");
      out.write("\t\t\tvar nTop = curY + (curHeight / 2) - (nHeight / 2);\r\n");
      out.write("\t\t\twindow.name = action;\r\n");
      out.write("\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search/\" + action + \".do\",\r\n");
      out.write("\t\t\t\t\t\"searchTable\",\r\n");
      out.write("\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\tpopup.addEventListener('beforeunload', function(){\r\n");
      out.write("\t\t\t\tcode.val($(\"#code\").val());\r\n");
      out.write("\t\t\t\tnm.val($(\"#nm\").val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#list-table\").on(\"click\", \".draftForm\", function(){\r\n");
      out.write("\t\t\tvacstusCode = $(this).parents(\"tr\").data(\"vacApply\").vacstusCode;\r\n");
      out.write("\t\t\tdraftTitle = \"휴가신청서_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empl.emplNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t$(\"#draftTitle\").val(draftTitle);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApplyDraft.do?what=' + vacstusCode,\r\n");
      out.write("\t\t\t\tdataType: \"html\"\r\n");
      out.write("\t\t\t}).done(function(res){\r\n");
      out.write("\t\t\t\tlocalStorage.setItem(\"draftContent\", res);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar nWidth = 1100;\r\n");
      out.write("\t\t\tvar nHeight = 1000;\r\n");
      out.write("\t\t\tvar curX = window.screenLeft;\r\n");
      out.write("\t\t\tvar curY = window.screenTop;\r\n");
      out.write("\t\t\tvar curWidth = document.body.clientWidth;\r\n");
      out.write("\t\t\tvar curHeight = document.body.clientHeight;\r\n");
      out.write("\t\t\tvar nLeft = curX + (curWidth / 2) - (nWidth / 2);\r\n");
      out.write("\t\t\tvar nTop = curY + (curHeight / 2) - (nHeight / 2);\r\n");
      out.write("\t\t\twindow.name =\"vacApplyInsert\";\r\n");
      out.write("\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/group/esign/draftForm.do?command=INSERT&formNo=6&chit=com.eg.vacation.service.VacService&code=\" + vacstusCode,\r\n");
      out.write("\t\t\t\t\t\"taxFree\",\r\n");
      out.write("\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\tpopup.addEventListener('beforeunload', function(){\r\n");
      out.write("\t\t\t\tsearchForm.submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#searchUI input[type=reset]\").on(\"click\", function(){\r\n");
      out.write("\t\t\t$(\"#searchUI input[type=hidden]\").val(\"\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).ajaxComplete(function(event, xhr, options){\r\n");
      out.write("\t\t\tsearchForm.find(\"[name='page']\").val(\"\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tlet tbody = $(\"#list-table tbody\");\r\n");
      out.write("\t\tlet pagingArea = $(\"#pagingArea\");\r\n");
      out.write("\t\tlet searchForm = $(\"#searchForm\").paging().ajaxForm({\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApply.do\",\r\n");
      out.write("\t\t\tsuccess: function(pagingVO){\r\n");
      out.write("\t\t\t\ttbody.empty();\r\n");
      out.write("\t\t\t\tpagingArea.empty();\r\n");
      out.write("\t\t\t\tlet vacApplyList = pagingVO.dataList;\r\n");
      out.write("\t\t\t\tlet trTags = [];\r\n");
      out.write("\t\t\t\tif(vacApplyList.length > 0){\r\n");
      out.write("\t\t\t\t\t$(vacApplyList).each(function(idx, vacApply){\r\n");
      out.write("\t\t\t\t\t\thalfAt = \"-\";\r\n");
      out.write("\t\t\t\t\t\tif(vacApply.vacstusHalfAt == 'Yes'){\r\n");
      out.write("\t\t\t\t\t\t\thalfAt = \"Y\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(vacApply.draft == null){\r\n");
      out.write("\t\t\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(vacApply.vacation.vcatnNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(vacApply.vacstusPeriod),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td class='selectDetail'>\").html(vacApply.vacstusSumry),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(halfAt),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(\"<a class='draftForm'>결재받기</a>\")\r\n");
      out.write("\t\t\t\t\t\t\t\t).data(\"vacApply\", vacApply)\r\n");
      out.write("\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t\tidxs = idx;\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"black\";\r\n");
      out.write("\t\t\t\t\t\t\tif(vacApply.draft.draftProgress == '결재완료'){\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor = \"green\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(vacApply.vacation.vcatnNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(vacApply.vacstusPeriod),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td class='selectDetail'>\").html(vacApply.vacstusSumry),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(halfAt),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"<td>\").html(vacApply.draft.draftProgress).css(\"color\", color)\r\n");
      out.write("\t\t\t\t\t\t\t\t).data(\"vacApply\", vacApply)\r\n");
      out.write("\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t\tidxs = idx;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\twhile(idxs < 15){\r\n");
      out.write("\t\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").attr(\"colspan\", \"5\").css(\"border\", \"none\")\r\n");
      out.write("\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\tidxs++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tpagingArea.html(pagingVO.pagingHTML);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t$(\"<tr>\").html(\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<td>\").attr(\"colspan\", \"5\").html(\"휴가신청내역이 없습니다.\")\r\n");
      out.write("\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ttbody.append(trTags);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#insert\").on(\"click\", function(){\r\n");
      out.write("\t\t\tvar nWidth = 700;\r\n");
      out.write("\t\t\tvar nHeight = 500;\r\n");
      out.write("\t\t\tvar curX = window.screenLeft;\r\n");
      out.write("\t\t\tvar curY = window.screenTop;\r\n");
      out.write("\t\t\tvar curWidth = document.body.clientWidth;\r\n");
      out.write("\t\t\tvar curHeight = document.body.clientHeight;\r\n");
      out.write("\t\t\tvar nLeft = curX + (curWidth / 2) - (nWidth / 2);\r\n");
      out.write("\t\t\tvar nTop = curY + (curHeight / 2) - (nHeight / 2);\r\n");
      out.write("\t\t\twindow.name =\"vacApplyInsert\";\r\n");
      out.write("\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApplyInsert.do\",\r\n");
      out.write("\t\t\t\t\t\"taxFree\",\r\n");
      out.write("\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\tpopup.addEventListener('beforeunload', function(){\r\n");
      out.write("\t\t\t\tsearchForm.submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \".selectDetail\", function(){\r\n");
      out.write("\t\t\tvacstusCode = $(this).parent().data(\"vacApply\").vacstusCode;\r\n");
      out.write("\t\t\tselectDetail = $(this).parents(\"tr\").find(\"td\");\r\n");
      out.write("\t\t\tselectDetail.css(\"background\", \"#FEFAE5\");\r\n");
      out.write("\t\t\tselectDetail.not(\".selectDetail\").css(\"color\", \"#AAAAAA\");\r\n");
      out.write("\t\t\tvar nWidth = 700;\r\n");
      out.write("\t\t\tvar nHeight = 500;\r\n");
      out.write("\t\t\tvar curX = window.screenLeft;\r\n");
      out.write("\t\t\tvar curY = window.screenTop;\r\n");
      out.write("\t\t\tvar curWidth = document.body.clientWidth;\r\n");
      out.write("\t\t\tvar curHeight = document.body.clientHeight;\r\n");
      out.write("\t\t\tvar nLeft = curX + (curWidth / 2) - (nWidth / 2);\r\n");
      out.write("\t\t\tvar nTop = curY + (curHeight / 2) - (nHeight / 2);\r\n");
      out.write("\t\t\tdraft = $(this).parent().data(\"vacApply\").draft;\r\n");
      out.write("\t\t\twindow.name =\"vacApplyUpdate\";\r\n");
      out.write("\t\t\tif(draft == null){\r\n");
      out.write("\t\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApplyUpdate.do?vacstusCode=\" + vacstusCode + \"&command=VIEW\",\r\n");
      out.write("\t\t\t\t\t\t\"draftDetail\",\r\n");
      out.write("\t\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif(draft.draftProgress == '임시저장'){\r\n");
      out.write("\t\t\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApplyUpdate.do?vacstusCode=\" + vacstusCode + \"&command=VIEW\",\r\n");
      out.write("\t\t\t\t\t\t\t\"draftDetail\",\r\n");
      out.write("\t\t\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vac/vacApplyUpdate.do?vacstusCode=\"+vacstusCode+\"&view=VIEW\",\r\n");
      out.write("\t\t\t\t\t\t\t\"draftDetail\",\r\n");
      out.write("\t\t\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tpopup.addEventListener('beforeunload', function(){\r\n");
      out.write("\t\t\t\tselectDetail.css({\"background\":\"transparent\"});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
