/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-01-25 06:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.gnfd;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gnfdStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640756830000L));
    _jspx_dependants.put("jar:file:/D:/B_Util/5.ApacheTomcat/apache-tomcat-8.5.37/webapps/eggegg/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/list.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/status.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t<span id=\"title\">인사발령현황</span>\r\n");
      out.write("\t\t<input id=\"searchButton\" type=\"button\" value=\"상세검색\">\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"searchUI\" class=\"searchDetail\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t발령일자\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"dateForm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"gnfdStartDe\" type=\"date\">&ensp;~&ensp;<input name=\"gnfdEndDe\" type=\"date\">&ensp;\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"useButton\" type=\"checkbox\">&ensp;사용\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t사원\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" class=\"code\" name=\"emplNo\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"small-search\" data-action=\"emplSearch\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"searchImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Search.png\">\r\n");
      out.write("\t\t\t\t\t\t\t</button><input type=\"text\" class=\"nm\" name=\"emplNm\" placeholder=\"사원\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>발령구분</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"gnfdType\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value>== 발령구분 ==</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>적요</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"gnfdSumry\" type=\"text\" placeholder=\"적요\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"searchBtn\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"초기화\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"main-table\">\r\n");
      out.write("\t\t<p id=\"statusTitle\">인사발령현황</p>\r\n");
      out.write("\t\t<table id=\"list-table\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>발령코드</th>\r\n");
      out.write("\t\t\t\t\t<th>발령일자</th>\r\n");
      out.write("\t\t\t\t\t<th>사번</th>\r\n");
      out.write("\t\t\t\t\t<th>사원명</th>\r\n");
      out.write("\t\t\t\t\t<th>발령구분명</th>\r\n");
      out.write("\t\t\t\t\t<th>이전 직위/직급</th>\r\n");
      out.write("\t\t\t\t\t<th>발령 직위/직급</th>\r\n");
      out.write("\t\t\t\t\t<th>이전 부서</th>\r\n");
      out.write("\t\t\t\t\t<th>발령 부서</th>\r\n");
      out.write("\t\t\t\t\t<th>적요</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form id=\"searchForm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gnfdStartDe\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.gnfdStartDe }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gnfdEndDe\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.gnfdEndDe }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"emplNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.emplNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gnfdType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.gnfdType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gnfdSumry\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pagingVO.detailSearch.gnfdSumry }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"bottom\">\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t\t<input type=\"button\" id=\"excel\" value=\"Excel다운로드\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"background\"></div>\r\n");
      out.write("<input type=\"hidden\" id=\"code\">\r\n");
      out.write("<input type=\"hidden\" id=\"nm\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/paging.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t//검색 버튼 클릭 시 검색창 닫음\r\n");
      out.write("\t\t$(\"#searchBtn\").on(\"click\", function(){\r\n");
      out.write("\t\t\tsearchUI.slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//검색 버튼\r\n");
      out.write("\t\t$(\".small-search\").on(\"click\", function(){\r\n");
      out.write("\t\t\taction = $(this).data(\"action\");\r\n");
      out.write("\t\t\tcode = $(this).parents(\"td\").find(\".code\");\r\n");
      out.write("\t\t\tnm = $(this).parents(\"td\").find(\".nm\");\r\n");
      out.write("\t\t\tvar nWidth = 900;\r\n");
      out.write("\t\t\tvar nHeight = 950;\r\n");
      out.write("\t\t\tvar curX = window.screenLeft;\r\n");
      out.write("\t\t\tvar curY = window.screenTop;\r\n");
      out.write("\t\t\tvar curWidth = document.body.clientWidth;\r\n");
      out.write("\t\t\tvar curHeight = document.body.clientHeight;\r\n");
      out.write("\t\t\tvar nLeft = curX + (curWidth / 2) - (nWidth / 2);\r\n");
      out.write("\t\t\tvar nTop = curY + (curHeight / 2) - (nHeight / 2);\r\n");
      out.write("\t\t\twindow.name = action;\r\n");
      out.write("\t\t\tpopup = window.open(\r\n");
      out.write("\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search/\" + action + \".do\",\r\n");
      out.write("\t\t\t\t\t\"searchTable\",\r\n");
      out.write("\t\t\t\t\t\"status=no, resizable=no, menubar=no,toolbar=no, location=no, scrollbars=no ,height=\" + nHeight  + \"px, width=\" + nWidth  + \"px, left=\"+ nLeft + \"px, top=\"+ nTop+\"px\");\r\n");
      out.write("\t\t\tpopup.addEventListener('beforeunload', function(){\r\n");
      out.write("\t\t\t\tcode.val($(\"#code\").val());\r\n");
      out.write("\t\t\t\tnm.val($(\"#nm\").val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#excel\").on(\"click\", function(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/empl/gnfdExcel.do\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//검색 초기화\r\n");
      out.write("\t\t$(document).ajaxComplete(function(event, xhr, options){\r\n");
      out.write("\t\t\t//검색단어 표시\r\n");
      out.write("\t\t\t$(\"#searchUI input[type=text]\").each(function(){\r\n");
      out.write("\t\t\t\tvar classNm = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar searchVal = $(this).val();\r\n");
      out.write("\t\t\t\t$(\".\"+classNm+\":contains('\"+searchVal+\"')\", tbody).each(function(){\r\n");
      out.write("\t\t\t\t\tvar regex = new RegExp(searchVal, 'gi');\r\n");
      out.write("\t\t\t\t\t$(this).html($(this).text().replace(regex, \"<span style='font-weight: bold; color: green;'>\"+searchVal+\"</span>\"));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#searchUI select\").each(function(){\r\n");
      out.write("\t\t\t\tvar classNm = $(this).attr(\"name\");\r\n");
      out.write("\t\t\t\tvar searchVal = $(this).find(\"option:selected\").html();\r\n");
      out.write("\t\t\t\t$(\".\"+classNm+\":contains('\"+searchVal+\"')\", tbody).each(function(){\r\n");
      out.write("\t\t\t\t\tvar regex = new RegExp(searchVal, 'gi');\r\n");
      out.write("\t\t\t\t\t$(this).html($(this).text().replace(regex, \"<span style='font-weight: bold; color: green;'>\"+searchVal+\"</span>\"));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tsearchForm.get(0).reset();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#searchUI input[type=reset]\").on(\"click\", function(){\r\n");
      out.write("\t\t\t$(\"#searchUI input[type=hidden]\").val(\"\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tlet tbody = $(\"#list-table tbody\");\r\n");
      out.write("\t\tlet searchForm = $(\"#searchForm\").paging().ajaxForm({\r\n");
      out.write("\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/empl/gnfdStatus.do\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(pagingVO){\r\n");
      out.write("\t\t\t\ttbody.empty();\r\n");
      out.write("\t\t\t\tlet gnfdList = pagingVO.dataList;\r\n");
      out.write("\t\t\t\tlet trTags = [];\r\n");
      out.write("\t\t\t\tif(gnfdList.length > 0){\r\n");
      out.write("\t\t\t\t\t$(gnfdList).each(function(idx, gnfd){\r\n");
      out.write("\t\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.gnfdStdrde),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.gnfdDe),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.emplNo),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td class='emplNm'>\").html(gnfd.empl.emplNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td class='gnfdType'>\").html(gnfd.gnfd.ctNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.gnfdBposition),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.position.pstNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.deptBnm),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td>\").html(gnfd.dept.deptNm),\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"<td class='gnfdSumry'>\").html(gnfd.gnfdSumry)\r\n");
      out.write("\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t\tidxs = idx+1;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<td>\").html(\"사원 수\").attr(\"colspan\", \"9\"),\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<td>\").html(idxs)\r\n");
      out.write("\t\t\t\t\t\t).css(\"background\", \"#FCFCFE\")\r\n");
      out.write("\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttrTags.push(\r\n");
      out.write("\t\t\t\t\t\t$(\"<tr>\").append(\r\n");
      out.write("\t\t\t\t\t\t\t$(\"<td>\").attr(\"colspan\", \"10\").html(\"조건에 맞는 인사발령내역이 없습니다.\")\r\n");
      out.write("\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ttbody.append(trTags);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).submit();\r\n");
      out.write("\t\t//검색창 slide\r\n");
      out.write("\t\tlet searchUI = $(\".searchDetail\").hide();\r\n");
      out.write("\t\t$(\"#searchButton\").on(\"click\", function(){\r\n");
      out.write("\t\t\tif(searchUI.is(\":visible\")){\r\n");
      out.write("\t\t\t\tsearchUI.slideUp();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tsearchUI.slideDown();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttoday = new Date();\r\n");
      out.write("\t\tstartDate = new Date(today.getFullYear(), today.getMonth()-1, 2);\r\n");
      out.write("\t\ttoday = today.toISOString().slice(0, 10);\r\n");
      out.write("\t\tstartDate = startDate.toISOString().slice(0, 10);\r\n");
      out.write("\t\t//검색창 입사일자 사용\r\n");
      out.write("\t\tlet dateForm = $(\".dateForm\").hide();\r\n");
      out.write("\t\t$(\".useButton\").change(function(){\r\n");
      out.write("\t\t\tif($(this).is(\":checked\")){\r\n");
      out.write("\t\t\t\t$(this).parent().find(dateForm).show();\r\n");
      out.write("\t\t\t\t$(this).parent().find(\"input:first-child\").val(startDate);\r\n");
      out.write("\t\t\t\t$(this).parent().find(\"input:last-child\").val(today);\r\n");
      out.write("\t\t\t} else if(!$(this).is(\":checked\")) {\r\n");
      out.write("\t\t\t\t$(this).parent().find(dateForm).hide();\r\n");
      out.write("\t\t\t\t$(this).find(\"input\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/gnfd/gnfdStatus.jsp(50,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/gnfd/gnfdStatus.jsp(50,8) '${ gnfdTypeList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ gnfdTypeList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/gnfd/gnfdStatus.jsp(50,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("gnfdType");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ gnfdType.ctTable }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ gnfdType.ctNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
