/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-01-25 06:32:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.esign;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class draftFormList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640756830000L));
    _jspx_dependants.put("jar:file:/D:/B_Util/5.ApacheTomcat/apache-tomcat-8.5.37/webapps/eggegg/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/paging.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/html2canvas.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/list.css\">\r\n");
      out.write("<style>\r\n");
      out.write("html,body{\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("#draftFormList{\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: 400px 400px 400px;\r\n");
      out.write("    gap: 0 50px;\r\n");
      out.write("    width: 1400px;\r\n");
      out.write("    height: 670px;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("#title {\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#bottom{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 28px;\r\n");
      out.write("}\r\n");
      out.write("#searchUI{\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tpadding-right: 240px;\r\n");
      out.write("}\r\n");
      out.write(".item div *{\r\n");
      out.write("\ttransform-origin: top left;\r\n");
      out.write("}\r\n");
      out.write(".item div table{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write(".item{\r\n");
      out.write("\theight: 285px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\toverflow:auto;\r\n");
      out.write("\tborder : 1px solid #EAEAEA;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item::-webkit-scrollbar {\r\n");
      out.write("    display: none; \r\n");
      out.write("}\r\n");
      out.write(".item canvas{\r\n");
      out.write("\tmargin: 0 12%;\r\n");
      out.write("}\r\n");
      out.write("tbody th, td{\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write(".item>span{\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\ttext-underline-position: under;\r\n");
      out.write("\tcolor: #3a4ca8\r\n");
      out.write("}\r\n");
      out.write(".resetBtn{\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\theight: 33px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".cForm{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    bottom: 11px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("canvas{\r\n");
      out.write("\ttransform: scale(0.3);\r\n");
      out.write("}\r\n");
      out.write("#newBtn, #searchBtn {\r\n");
      out.write("    background: #3A4CA8;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tpadding: 1px 10px;\r\n");
      out.write("\tmargin: 2px 0px 2px 10px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("#title{\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("hr {\r\n");
      out.write("    margin: 5px 0px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".capture table{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("#bottom{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tbottom: 75px;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("\t\t&ensp;&ensp;&ensp;\r\n");
      out.write("\t\t<span id=\"title\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"searchUI\">\r\n");
      out.write("\t\t <input type=\"text\" name=\"dfTitle\" placeholder=\"양식명으로 검색\" id=\"searchInput\"> \r\n");
      out.write("\t\t <button type=\"button\" id=\"searchBtn\">검색</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<form id=\"deleteForm\">\r\n");
      out.write("\t\t\t<div id=\"draftFormList\">\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item1\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item2\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item3\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item4\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item5\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item6\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form id=\"searchForm\" hidden>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"page\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"dfTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailSearch.dfTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"pagingArea\"></div>\r\n");
      out.write("\t<div id=\"bottom\">\r\n");
      out.write("\t\t<hr color=\"#F1F4FF\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.command }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-action=\"draftForm.do?command=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.command }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&formNo=0\" id=\"newBtn\">신규</button>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t//리스트\r\n");
      out.write("command = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.command}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("function reload (){\r\n");
      out.write("\tvar itemList = $(\".item\");\r\n");
      out.write("\tlet tbody = $(\"#list-table tbody\");\r\n");
      out.write("\tlet pagingArea = $(\"#pagingArea\");\r\n");
      out.write("\tlet searchForm = $(\"#searchForm\");\r\n");
      out.write("\tsearchForm.paging().ajaxForm({\r\n");
      out.write("\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/group/esign/draftFormList.do\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: function(pagingVO){\r\n");
      out.write("\t\t\t$.each(itemList,function(i,v){\r\n");
      out.write("\t\t\t\t$(v).empty();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tpagingArea.empty();\r\n");
      out.write("\t\t\tlet draftFormList = pagingVO.dataList;\r\n");
      out.write("\t\t\tif(draftFormList.length > 0){\r\n");
      out.write("\t\t\t\t$(draftFormList).each(function(idx, draftForm){\r\n");
      out.write("\t\t\t\t\tvar formNo = draftForm.dfNo;\r\n");
      out.write("\t\t\t\t\tvar draftTitle = draftForm.dfTitle;\r\n");
      out.write("\t\t\t\t\tvar draftContent = draftForm.dfContent;\r\n");
      out.write("\t\t\t\t\tvar item = itemList[idx];\r\n");
      out.write("\t\t\t\t\tvar cForm = (draftForm.emplNo == '9999999')?\"<br><span class=cForm>[공통양식]</span>\":\"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(item).empty()\r\n");
      out.write("\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t$(\"<span class='title'>\").html(draftTitle+cForm)\r\n");
      out.write("\t\t\t\t\t\t.attr(\"class\",command).attr(\"data-action\",\"draftForm.do?command=\"+command+\"&formNo=\"+formNo)\r\n");
      out.write("\t\t\t\t\t\t.css(\"cursor\",\"pointer\")\r\n");
      out.write("\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t$(\"<div>\").attr(\"class\",draftForm.dfUse)\r\n");
      out.write("\t\t\t\t\t\t.css(\"overflow\",\"hidden\").css(\"height\",\"auto\"));\r\n");
      out.write("\t\t\t\t\tif(command == 'UPDATE')\t{$(item).prepend($(\"<input type='checkbox' name='deleteDfNo' value='\"+formNo+\"'>\").css(\"transform\",\"scale(1.7) translate(-10px, 0px)\"))};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"main\").append($(\"<div class='capture'>\").html(draftContent).css(\"width\",\"1000px\").css(\"position\",\"relative\").css(\"left\",\"2000px\").css(\"bottom\",\"800px\").css(\"white-space\",\"nowrap\"));\r\n");
      out.write("\t\t\t\t });\r\n");
      out.write("\t\t\t\tdraw();\r\n");
      out.write("\t\t\t\tpagingArea.html(pagingVO.pagingHTML);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#draftFormList\").empty().html(\"등록된 양식이 없습니다.\").css(\"text-align\",\"center\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}).submit();\r\n");
      out.write("\t\r\n");
      out.write("\treturn \"ok\";\r\n");
      out.write("}\r\n");
      out.write("\t\treload();\r\n");
      out.write("\t\tfunction draw(){\r\n");
      out.write("\t\t\tcaptureList = $(\".capture\");\r\n");
      out.write("\t\t\thtml2canvas(captureList[0],{\r\n");
      out.write("\t\t\t\tscale : 0.5\r\n");
      out.write("\t\t\t}).then(canvas=>{\r\n");
      out.write("\t\t\t\t$(\"#item1>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[0].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\thtml2canvas(captureList[1]).then(function(canvas){\r\n");
      out.write("\t\t\t\t$(\"#item2>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[1].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\thtml2canvas(captureList[2]).then(function(canvas){\r\n");
      out.write("\t\t\t\t$(\"#item3>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[2].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\thtml2canvas(captureList[3]).then(function(canvas){\r\n");
      out.write("\t\t\t\t$(\"#item4>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[3].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\thtml2canvas(captureList[4]).then(function(canvas){\r\n");
      out.write("\t\t\t\t$(\"#item5>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[4].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\thtml2canvas(captureList[5]).then(function(canvas){\r\n");
      out.write("\t\t\t\t$(\"#item6>div\").empty().html(canvas);\r\n");
      out.write("\t\t\t\tcaptureList[5].remove();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//일괄삭제버튼 클릭시\r\n");
      out.write("\t\t$(\"#deleteBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\"#deleteForm\").ajaxForm({\r\n");
      out.write("\t\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/group/esign/draftFormDelete.do\",\r\n");
      out.write("\t\t\t\tmethod : \"POST\",\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(res.result == \"OK\"||res.result == \"FAIL\") {\r\n");
      out.write("\t\t\t\t\t\t\tmessage = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t$.each(res.failDfNo,function(i,v){\r\n");
      out.write("\t\t\t\t\t\t\t\tmessage += this +\"번 양식\"\r\n");
      out.write("\t\t\t\t\t\t\t\tif(res.failDfNo.length-1 != i) message += \",\";\r\n");
      out.write("\t\t\t\t\t\t\t\tmessage += \"삭제 실패(본인소유 양식이 아님.)\";\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t(res.deleteCnt==undefined)?res.deleteCnt=0:res.deleteCnt=res.deleteCnt;\r\n");
      out.write("\t\t\t\t\t\t\tmessage += \"\\n 선택 갯수 \"+ (res.failDfNo.length + res.deleteCnt) +\"개 중 삭제 갯수 : \" + res.deleteCnt; \r\n");
      out.write("\t\t\t\t\t\t\tif(res.deleteCnt != 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"input[name='page']\").val(1);\r\n");
      out.write("\t\t\t\t\t\t\t\treload();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\talert(message);\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"에러 발생, 개발자에게 문의해주세요.\")\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t// 양식명 클릭 시 상세로 들어감.\r\n");
      out.write("\t$(document).on(\"click\",\".\"+command,function(){\r\n");
      out.write("\t\taction=$(this).data(\"action\");\r\n");
      out.write("\t\twindow.name = action;\r\n");
      out.write("\t\twindow.open(\r\n");
      out.write("\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ cPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/group/esign/\" + action,\r\n");
      out.write("\t\t\t\"draftDetail\",\r\n");
      out.write("\t\t\t\"status=no, resizable=no, menubar=no, toolbar=no, location=no, scrollbars=no, height= 900px, width=1130px, left=500px, top=30px\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}); // $function end\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/esign/draftFormList.jsp(113,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.command eq 'UPDATE'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t결재 양식 목록\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t기안 양식 선택\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/esign/draftFormList.jsp(147,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.command eq 'UPDATE' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<button type=\"button\" class=\"resetBtn\" id=\"deleteBtn\">일괄삭제</button>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
